"""Agregar columna final_penalty a Loan

Revision ID: 3150ca41ef16
Revises: b59025886807
Create Date: 2026-02-24 10:57:45.686959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3150ca41ef16'
down_revision = 'b59025886807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_penalty', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('final_penalty')

    # ### end Alembic commands ###
