"""Migración inicial a Postgres

Revision ID: 7d5176a3645a
Revises: 
Create Date: 2026-03-09 11:33:41.793708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5176a3645a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_or_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('author_or_brand', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_name', sa.String(length=100), nullable=False),
    sa.Column('visitor_id', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('activity', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('document_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('program_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('item_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('unique_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'LOANED', 'MAINTENANCE', 'LOST', name='inventory_status_enum', create_constraint=True), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_code')
    )
    with op.batch_alter_table('item_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_instance_catalog_id'), ['catalog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_instance_status'), ['status'], unique=False)

    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'OVERDUE', 'RETURNED', 'REJECTED', name='loan_status_enum', create_constraint=True), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('final_penalty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['item_instance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_user_id'))
        batch_op.drop_index(batch_op.f('ix_loan_status'))
        batch_op.drop_index(batch_op.f('ix_loan_instance_id'))

    op.drop_table('loan')
    with op.batch_alter_table('item_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_instance_status'))
        batch_op.drop_index(batch_op.f('ix_item_instance_catalog_id'))

    op.drop_table('item_instance')
    op.drop_table('user')
    op.drop_table('library_log')
    op.drop_table('catalog')
    # ### end Alembic commands ###
