"""Agregar columna is_penalty_applicable a la tabla catalog

Revision ID: f238d95d2303
Revises: 7d5176a3645a
Create Date: 2026-04-09 14:52:52.141238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f238d95d2303'
down_revision = '7d5176a3645a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_penalty_applicable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.drop_column('is_penalty_applicable')

    # ### end Alembic commands ###
